steps:

# Build backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - australia-southeast1-docker.pkg.dev/sit323-26t1-parfitt-ca-44e3bf5/my-repo/backend:latest
    - ./backend

# Push backend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - australia-southeast1-docker.pkg.dev/sit323-26t1-parfitt-ca-44e3bf5/my-repo/backend:latest

# Build frontend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - australia-southeast1-docker.pkg.dev/sit323-26t1-parfitt-ca-44e3bf5/my-repo/frontend:latest
    - ./frontend

# Push frontend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - australia-southeast1-docker.pkg.dev/sit323-26t1-parfitt-ca-44e3bf5/my-repo/frontend:latest

images:
  - australia-southeast1-docker.pkg.dev/sit323-26t1-parfitt-ca-44e3bf5/my-repo/backend:latest
  - australia-southeast1-docker.pkg.dev/sit323-26t1-parfitt-ca-44e3bf5/my-repo/frontend:latest

options:
  logging: CLOUD_LOGGING_ONLY